suffix: "mixed" #std or mixed
train_class_size: 500
eval_class_size: 100
real_train_class_size: 50
real_eval_class_size: 25
num_classes: 3
num_epochs: 200

model_configs:
  - name: effnetv2
    model_index: 0
    batch_size: 32
    lr: 0.001
    load_weights: False
    skip: False
  - name: vit
    model_index: 1
    batch_size: 24
    lr: 0.001
    load_weights: False
    skip: False
  - name: convNext
    model_index: 2
    batch_size: 32
    lr: 0.001
    load_weights: False
    skip: False
  - name: swinV2
    model_index: 3
    batch_size: 24
    lr: 0.001
    load_weights: False
    skip: False
